### ISSUE TITLE
No support or contact

### ISSUE THREAD

**Issue by igalic** [fluent/website#4]
Hi folks,

the website http://fluentd.org/doc/ does _not_ list any means of contacting developers or users, such as mailing lists or an IRC channel.

Of course there's GitHub's issue tracker here, but this involves a bit of a thought process so not writing that on the website also makes it unclear.

You don't have to run your own mailing lists - just like you don't have to run your own IRC server (FreeNode, Oftc are all very FOSS friendly).
For mailing lists, there's Zed Shaw's http://librelist.com/

But please, please, please consider starting lists for users (and maybe plugin developers)

Open Source without support is bad :(and open source without transparency for developers is just as bad).:

So long,

i

**Comment by frsyuki** [comment]
Hi igalic, 

First, apologies for taking so long to get back to you.

We discussed the appropriateness of various options, including mailing lists or an IRC channel during this time. However, at this time we are not set up to properly and responsibly operate either of these in a manner that we are happy with. We don't want to set either option up, then abandon our developer community there. However, when we have the resources to responsibly operate these avenues, we will definitely do so, as we are aware that these are the traditional means of communication for developers. 

At this time, fluentd's developers are using Twitter to communicate with one another by using the tag: #fluentd

We know that this is a stopgap solution, but I hope that it can satisfy your needs, at least partially, for the time being. 

Thanks for your feedback and support.

Best regards,
Sadayuki

**Comment by kzk** [comment]
> http://groups.google.com/group/fluentd

Google Groups is finally created. Please join! @igalic
